
services:
  frontend:
    image: raknark/sdj-frontend:latest
    container_name: frontend-angular
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - valhalla_net

  backend:
    image: raknark/sdj-backend:latest
    container_name: sdj-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=valhalla
      - DB_USERNAME=root
      - DB_PASSWORD=
    networks:
      - valhalla_net



  db:
    image: raknark/sdj-db:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: valhalla
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d
    networks:
      - valhalla_net

volumes:
  db_data:

networks:
  valhalla_net: